import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://rabet-alkhayal.com'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/ar/',
          '/en/',
          '/ar/products/',
          '/en/products/',
          '/ar/services/',
          '/en/services/',
          '/ar/categories/',
          '/en/categories/',
          '/ar/about/',
          '/en/about/',
          '/ar/contact/',
          '/en/contact/',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/auth/',
          '/my-orders/',
          '/my-profile/',
          '/cart/',
          '/wishlist/',
          '/verify-otp/',
          '/payment/',
          '/auth/google/callback/',
          '/ar/payment/',
          '/en/payment/',
          '/ar/auth/',
          '/en/auth/',
          '/ar/my-orders/',
          '/en/my-orders/',
          '/ar/my-profile/',
          '/en/my-profile/',
          '/ar/cart/',
          '/en/cart/',
          '/ar/wishlist/',
          '/en/wishlist/',
          '/ar/verify-otp/',
          '/en/verify-otp/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/ar/',
          '/en/',
          '/ar/products/',
          '/en/products/',
          '/ar/services/',
          '/en/services/',
          '/ar/categories/',
          '/en/categories/',
          '/ar/about/',
          '/en/about/',
          '/ar/contact/',
          '/en/contact/',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/auth/',
          '/my-orders/',
          '/my-profile/',
          '/cart/',
          '/wishlist/',
          '/verify-otp/',
          '/payment/',
          '/auth/google/callback/',
          '/ar/payment/',
          '/en/payment/',
          '/ar/auth/',
          '/en/auth/',
          '/ar/my-orders/',
          '/en/my-orders/',
          '/ar/my-profile/',
          '/en/my-profile/',
          '/ar/cart/',
          '/en/cart/',
          '/ar/wishlist/',
          '/en/wishlist/',
          '/ar/verify-otp/',
          '/en/verify-otp/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/ar/',
          '/en/',
          '/ar/products/',
          '/en/products/',
          '/ar/services/',
          '/en/services/',
          '/ar/categories/',
          '/en/categories/',
          '/ar/about/',
          '/en/about/',
          '/ar/contact/',
          '/en/contact/',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/auth/',
          '/my-orders/',
          '/my-profile/',
          '/cart/',
          '/wishlist/',
          '/verify-otp/',
          '/payment/',
          '/auth/google/callback/',
          '/ar/payment/',
          '/en/payment/',
          '/ar/auth/',
          '/en/auth/',
          '/ar/my-orders/',
          '/en/my-orders/',
          '/ar/my-profile/',
          '/en/my-profile/',
          '/ar/cart/',
          '/en/cart/',
          '/ar/wishlist/',
          '/en/wishlist/',
          '/ar/verify-otp/',
          '/en/verify-otp/',
        ],
        crawlDelay: 2,
      },
      {
        userAgent: 'facebookexternalhit',
        allow: [
          '/',
          '/ar/',
          '/en/',
          '/ar/products/',
          '/en/products/',
          '/ar/services/',
          '/en/services/',
          '/ar/categories/',
          '/en/categories/',
          '/ar/about/',
          '/en/about/',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/auth/',
          '/my-orders/',
          '/my-profile/',
          '/cart/',
          '/wishlist/',
          '/verify-otp/',
          '/payment/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
